version: '3.3'

services:

###########################################################

 itinerary-discovery-server:
  build: ./itinerary-discovery-server
  ports:
   - "8761:8761"
  tty:
    true
  restart:
    unless-stopped
  networks:
      - network-eureka

###########################################################

 itinerary-service:
  build: ./itinerary-service
  ports:
   - "8100" # Not port binding needed
  tty:
    true
  restart:
    unless-stopped
  networks:
   - network-eureka
  depends_on:
   - itinerary-discovery-server
  links:
   - itinerary-discovery-server
  environment:
   - SPRING_PROFILES_ACTIVE=dev

###########################################################

 trip-selector-service:
  build: ./trip-selector-service
  ports:
   - "8200". # Not portbinding needed. - Zuul will fetch by name
  environment:
   - SPRING_PROFILES_ACTIVE=dev
  tty:
    true
  restart:
    unless-stopped
  networks:
   - network-eureka
  depends_on:
   - itinerary-discovery-server
  links:
   - itinerary-discovery-server

###########################################################

 zuul-gateway:
  build: ./zuul-gateway
  ports:
   - "8081:8081"
  environment:
   - SPRING_PROFILES_ACTIVE=dev
   - REGISTRY_HOST=itinerary-discovery-server
  tty:
   true
  networks:
   - network-eureka
  restart:
   unless-stopped
  depends_on:
   - itinerary-discovery-server
  links:
   - itinerary-discovery-server

###########################################################

networks:
  network-eureka:
    driver: bridge
 