# No ugly logging pollution, only errors
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
spring:
  devtools:
    add-properties: false
feign:
  hystrix:
    enabled: true
---
spring:
  application:
    name: trip-selector-service
  profiles:
    active: dev
server:
  port: 8200
eureka:
  client:
    serviceUrl:
      defaultZone: http://itinerary-discovery-server:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
    preferIpAddress: true
---
spring:
  profiles: local
  application:
    name: trip-selector-service
server:
  port: 8200
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
    preferIpAddress: true
