spring:
  application:
    name: trip-selector-service
feign:
  hystrix:
    enabled: true
server:
  port: 8200

eureka:
  client:
    serviceUrl:
      defaultZone: http://itinerary-discovery-server:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
    preferIpAddress: true
