spring:
  application:
    name: zuul-gateway
zuul:
  routes:
    ## Only routes the trip finder/selector service and authentication service
    trip-selector-service:
      path: '/trips-selector-api/**'
      serviceId: 'trip-selector-service'
    ignoredServices: '*'
server:
  port: ${PORT:8081}
---
spring:
  profiles:
    active: local
eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
    preferIpAddress: true
---
spring:
  profiles: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://${registry.host}:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 6000
  eureka:
    enabled: true