spring.application.name: itinerary-discovery-server
server.port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# No ugly logging pollution, if Eureka isn´t up or found
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF