# No ugly logging pollution, only errors
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: error
spring:
  devtools:
    add-properties: false
---
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    initialization-mode: always
    platform: h2
  application:
    name: itinerary-service

  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://itinerary-discovery-server:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
    preferIpAddress: true

server:
  port: 8100
---
spring:
  profiles: local
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    initialization-mode: always
    platform: h2
  application:
    name: itinerary-service

  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
    preferIpAddress: true

server:
  port: 8100
