spring:
  profiles:
    active: h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
